Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,7 +19,13 @@ jobs:
         with:
           node-version: latest
           cache: npm
-
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.IONOS_SFTP_HOST }}" ]; then echo "IONOS_SFTP_HOST is missing"; exit 1; fi
+          if [ -z "${{ secrets.IONOS_SFTP_USER }}" ]; then echo "IONOS_SFTP_USER is missing"; exit 1; fi
+          if [ -z "${{ secrets.IONOS_SFTP_PASSWORD }}" ]; then echo "IONOS_SFTP_PASSWORD is missing"; exit 1; fi
+          echo "Secrets are set"
+    
       - name: Install
         run: npm ci
 
